services:
  - type: web
    name: movie-infomation-app-laravel
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
